name: "Bug!"
description: "Identification of a new issue"
title: "[Bug]: "
labels: ["bug"]
assignees: 
  -abbylindsay

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug - actual behavior
      description: A clear and concise description of what you/the participant is seeing and why it is a problem. Include screenshots!
      placeholder: Help!
    validations:
      required: true
- type: textarea
    id: expected behavior
    attributes:
      label: What is the expected behavior?
      description: Be descriptive: what should be happening? Provide examples if possible (and screenshots!)
      placeholder: 
    validations:
      required: true
- type: textarea
    id: indentification
    attributes:
      label: How was this bug identified
      description: Who saw it? What was the context?
      placeholder: 
    validations:
      required: true
- type: textarea
    id: investigation
    attributes:
      label: Investigation so far
      description: What has been done thus far to resolve/investigate the bug? How to reproduce? 
      placeholder: 
    validations:
      required: true
- type: dropdown
    id: Priority
    attributes:
      label: Severity level
      description: 1- a V&V will not be run for this issue alone. 2- Want to have 3- Causing minor impact to study/participant 4- Causing big impact to study/participant 5- BAD BAD BAD
      multiple: false
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
     validations:
      required: true
- type: textarea
    id: context
    attributes:
      label: Additional Contect
      description: App version, firmware version, other information?
      placeholder: Please look it up
    validations:
      required: true
