name: "Development Template"
description: "Software development template for project issue breakdown"

body:
  - type: textarea
    attributes:
      label: Depends on
  - type: textarea
    attributes:
      label: What work needs to be done?
  - type: textarea
    attributes:
      label: Acceptance Criteria
  - type: textarea
    attributes:
      label: Implementation Details
  - type: textarea
    attributes:
      label: Additional information

    
