name: New Mason Project & Group
description: Create a new Mason project and group
title: "[MASON]: "
labels: ["mason"]
body:
  - type: input
    id: project
    attributes:
      label: Create the new projects and group for project
      placeholder: "BioDigit-MG"
    validations:
      required: true
  - type: markdown
    id: instructions
    attributes:
      value: A member of @biosensics/engineering may follow [BS-03-0048](https://biosenics.greenlight.guru/documents/6b42b337-2f77-4c43-b784-ef856b9b4131/effective-doc) to make the Mason groups/projects.
      description: "
        ## Project Creation
        Must match the application id, replacing underscores for hyphens. Then a hyphen followed by the instance of the project.
        For example:
        Raw Project Name: `BioDigit-MG`
        Application ID: `.biodigit_mg`
        Test Project: `BioDigit-MG-TEST`
        Production Project: `BioDigit-MG`"
      placeholder: "Any aditional information"
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Create the projects for
      description: Please select all instaces of the project to create
      options:
      - label: TEST
      - label: UAT
      - label: PRODUCTION
  - type: markdown
    attributes:
      value: |
        ## Group Creation 
        See the work instruction, on 5.4
  - type: checkboxes
    attributes:
      label: Create the groups for
      description: Please select all instances of the groups to create
      options:
      - label: develop
      - label: v-and-v
      - label: uat
      - label: production
      - type: markdown
    attributes:
      value: To be completed by the requestor once the request has been completed, then the requestor can close the issue. 
  - type: checkboxes
    id: confirm-testing
    attributes:
      label: Completion Checklist
      description: The assignee should check off each item as it is completed.
      options:
      - label: Mason Projects Created
      - label: Mason Groups Created
      - label: Mason Project build configs deployed, to the appropriate groups 
