name: "Software Release Request"
description: "Checklist for Software Version Release"
title: "[Software Release Request]: "
labels: ["request"]
assignees: 
  - jcarlosbarbosa

body:
  - type: markdown
    attributes:
      value: |
        [Link to ECO In Progress Folder](https://biosensics.app.box.com/folder/279871072773)
        **Note: For older projects with separate Application and Server repos, please open and link two separate V&V Execution Checklists, one for each ECO. In this case, the "Test Engineering - Execute V&V" task shall be crossed out on the Server V&V Execution Checklist.**
  - type: input
    attributes:
      label: What is the ECO number?
      description: "ECO Number"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Please describe the change being requested for this software version
      description: "Reason for request"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Specific due date?
      description: "Justification for given due date or type N/A"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any additional comments?
      description: "Any concerns or things to highlight prior to this specific run"
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Software Release Checklist - Attempt #1:" 
  - type: checkboxes
    id: build
    attributes:
      label: "Engineering"
      description: "Check once tasks are complete"
      options:
        - label: Create APK/IPA build 
        - label: Deploy test server
  - type: checkboxes
    id: test
    attributes:
      label: "Test Engineering"
      description: "Check once tasks are complete"
      options:
        - label: Test APK/IPA and/or server build
  - type: markdown
    attributes:
      value: "If previous attempt fails; copy and paste Software Release Checklist below and increment attempt #" 
  - type: markdown
    attributes:
      value: "##  ** Below to be completed after passing V&V **" 
  - type: checkboxes
    id: approved
    attributes:
      label: "Quality"
      description: "Check once tasks are complete"
      options:
        - label: Software is approved for release 
  - type: checkboxes
    id: eng
    attributes:
      label: "Engineering"
      description: "Check once tasks are complete"
      options:
        - label: Software release created and tagged 
        - label: Server deployed to production
        - label: Scale down test server
  - type: checkboxes
    id: room
    attributes:
      label: "Operations"
      description: "Check once tasks are complete"
      options:
        - label: Confirm telehealth meeting room is correct on release build (as applicable)
        - label: Confirm software is listed as most updated version on a device set up for the production environment
        - label: Confirm server is listed as most updated version on a device set up for the production environment
