name: SRS Section
description: Template for creating issues related to Section 5 of the SRS.
title: "<Project>: Section x.y"
labels: []
assignees:
  - juliemclarnon

body:
  - type: markdown
    attributes:
      value: "Please fill out this template to ensure a thorough review of the issue related to the SRS Section"

  - type: textarea
    id: summary
    attributes:
      label: Summary of SRS Section
      description: "Summarize the relevant part of the SRS for this issue."
      placeholder: "Provide a brief summary of the relevant SRS section here."
    validations:
      required: true

  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      description: "Mark these checkboxes as complete as these are completed."
      options:
        - label: Create subissues for detailed tasks
        - label: Fill out issue fields
        - label: Assign to team members
        - label: Link to relevant SRS documents

  - type: textarea
    id: srs-link
    attributes:
      label: References
      description: "Provide a link to the relevant SRS or any other document for reference"
      value: |
        - Reference 1
        - Reference 2
        - Reference 3
    validations:
      required: true

  - type: textarea
    id: developer-tasks
    attributes:
      label: Developer Tasks
      description: "In this section, the software team should list out all technical tasks required to satisfy this requirement section. These can be split up into groups based on logical or architectural groupings and can link to issues that detail some requirement."
      placeholder: "Add items here"
      value: |
        ## Backend
        [ ] Update schema to add some new field
        [ ] Modify report to include something
        ## Frontend
        [ ] Update alignment of popup text
    validations:
      required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: "Add any additional comments or notes regarding this issue."
      placeholder: "Add comments here."

