name: SRS Section
description: Template for creating issues related to Section 5 of the SRS.
title: "SRS Section x.x"
labels: ["SRS"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "Please fill out this template to ensure a thorough review of the issue related to the SRS Section"

  - type: input
    id: title
    attributes:
      label: Issue Title
      description: "Provide a concise title for the issue."
      placeholder: "Title"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary of SRS Section
      description: "Summarize the relevant part of the SRS for this issue."
      placeholder: "Provide a brief summary of the relevant SRS section here."
    validations:
      required: true

  - type: textarea
    id: subsection-details
    attributes:
      label: Subsection Details
      description: "Detail the specific subsections of the SRS Section related to this issue."
      placeholder: "Detail the subsections here."
    validations:
      required: true

  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      description: "Mark these checkboxes as complete as these are completed."
      options:
        - label: Create subissues for detailed tasks
        - label: Estimate level of effort
        - label: Assign to team members
        - label: Link to relevant SRS documents

  - type: input
    id: srs-link
    attributes:
      label: Link to SRS Document
      description: "Provide a link to the relevant SRS document for reference."
      placeholder: "http://"
    validations:
      required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: "Add any additional comments or notes regarding this issue."
      placeholder: "Add comments here."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: "Select the priority of this issue."
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
