name: System Requirements Specification Group Issue
description: Template for creating issues related to Section 5 of the System Requirements Specification.
title: "<Project>: Section 5.n"
labels: []
projects: "biosensics/64"
assignees:
  - "juliemclarnon"

body:
  - type: markdown
    attributes:
      value: |
        ## Issue Template for System Requirements Specification
        This template is designed to create issues related to specific sections of the System Requirements Specification (SRS). Follow the structure below to ensure all relevant information is included.

  - type: textarea
    id: summary
    attributes:
      label: Summary of System Requirements Specification Section
      description: "Summarize the relevant part of the System Requirements Specification for this issue."
      placeholder: "Provide a brief summary of the requirement here."
    validations:
      required: true

  - type: textarea
    id: srs-link
    attributes:
      label: References
      description: "Please add references here"
      placeholder: "e.g., [SRS Document](https://example.com/srs), [Related Issue](https://example.com/issue)"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        #### Example
        - [SRS Document](https://example.com/srs)
        - [QMG Form](https://myasthenia.org/Portals/0/QMG.pdf)

        ---
  
  - type: textarea
    id: developer-tasks
    attributes:
      label: Developer Tasks
      description: "Please list out the tasks required to satisfy this requirement"
      placeholder: "Add items here"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
       Example:
        
        ## Backend
        - [ ] Update schema to add some new field
        - [ ] Modify report to include something
        ## Frontend
        - [ ] Update alignment of popup text
        - [ ] Add new button to the UI
        
        ---

  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: "Add any additional comments or notes regarding this issue."
      placeholder: "Add comments here."

