name: System Requirements Specification Group Issue
description: Template for creating issues related to Section 5 of the System Requirements Specification.
title: "<Project>: Section 5.n"
labels: []
projects: "biosensics/64"
assignees:
  - "juliemclarnon"

body:
  - type: markdown
    attributes:
      value: |
        ## System Requirements Specification Section 5.n

        ### Issue Description
        Provide a description of the Requirement.  This should be a brief summary explaining the scope of this requirement section

        ### Example

  - type: textarea
    id: summary
    attributes:
      label: Summary of System Requirements Specification Section
      description: "Summarize the relevant part of the System Requirements Specification for this issue."
      placeholder: "Provide a brief summary of the requirement here."
      value: <!--- Summarize the relevant part of the System Requirements Specification for this issue. -->
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### References
        Provide a link to the relevant System Requirements Specification or any other documents for reference.  If possible these should be valid links.

        ### Example
        - [SRS](https://github.com/biosensics)
        - [Whimsical/Figma](https://whimsical.com/)
        - [QMG Form](https://myasthenia.org/Portals/0/QMG.pdf)

  - type: textarea
    id: srs-link
    attributes:
      label: References
      description: "Please add references here"
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        ### Developer Tasks
        In this section, the software team should list out all technical tasks required to satisfy this requirement section. These can be split up into groups based on logical or architectural groupings and can link to issues that detail some requirement.

        ### Example
        ## Backend
        - [ ] Update schema to add some new field
        - [ ] Modify report to include something
        ## Frontend
        - [ ] Update alignment of popup text
        - [ ] Add new button to the UI

  - type: textarea
    id: developer-tasks
    attributes:
      label: Developer Tasks
      description: "Please list out the tasks required to satisfy this requirement"
      placeholder: "Add items here"
    validations:
      required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: "Add any additional comments or notes regarding this issue."
      placeholder: "Add comments here."

