name: System Requirements Specification Group Issue
description: Template for creating issues related to Section 5 of the System Requirements Specification.
title: "<Project>: Section 5.n"
labels: []
projects: "biosensics/64"
assignees:
  - @biosensics/project-managers

body:
  - type: markdown
    attributes:
      value: "Please fill out this template to ensure a thorough review of the issue related to the System Requirements Specification"

  - type: textarea
    id: summary
    attributes:
      label: Summary of System Requirements Specification Section
      description: "Summarize the relevant part of the System Requirements Specification for this issue."
      placeholder: "Provide a brief summary of the relevant SRS section here."
    validations:
      required: true

  - type: textarea
    id: srs-link
    attributes:
      label: References
      description: "Provide a link to the relevant SRS or any other documents for reference.  If possible these should be valid links."
      value: |
        - [SRS](https://github.com/biosensics)
        - [Whimsical/Figma](https://whimsical.com/)
        - [QMG Form](https://myasthenia.org/Portals/0/QMG.pdf)
    validations:
      required: true

  - type: textarea
    id: developer-tasks
    attributes:
      label: Developer Tasks
      description: "In this section, the software team should list out all technical tasks required to satisfy this requirement section. These can be split up into groups based on logical or architectural groupings and can link to issues that detail some requirement."
      placeholder: "Add items here"
      value: |
        ## Backend
        - [ ] Update schema to add some new field
        - [ ] Modify report to include something
        ## Frontend
        - [ ] Update alignment of popup text
    validations:
      required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: "Add any additional comments or notes regarding this issue."
      placeholder: "Add comments here."

