name: "V&V Execution Checklist"
description: "Checklist for V&V Execution"
title: "[V&V]: "
labels: ["checklist"]
assignees: 
  - jcarlosbarbosa

body:
  - type: checkboxes
    attributes:
      label: "Operations"
      description: "Check once tasks are complete"
      options:
        - label: Request an ECO number and complete Section I
  - type: checkboxes
    attributes:
      label: "Engineering"
      description: "Check once tasks are complete"
      options:
        - label: Complete Section II of the ECO
  - type: checkboxes
    attributes:
      label: "Test"
      description: "Check once tasks are complete"
      options:
        - label: Complete Section III of the ECO
  - type: checkboxes
    attributes:
      label: "Quality"
      description: "Check once tasks are complete"
      options:
        - label: ECO approved 
  - type: checkboxes
    id: ops
    attributes:
      label: "Operations"
      description: "Check once tasks are complete"
      options:
        - label: Equipment set up for V&V execution (Details on parse account login, Device info - OS version, model name, build number)

  - type: checkboxes
    attributes:
      label: "Test Engineering"
      description: "Check once tasks are complete"
      options:
        - label: V&V Executed 
