name: "V&V Execution Checklist"
description: "Checklist for V&V Execution"
title: "[Checklist]: "
labels: ["checklist"]
assignees: 
  - scarter008

body:
  - type: textarea
    attributes:
      label: full or partial
      description: "Team lead determine if full or partial V&V is needed"
    validations:
      required: true
