name: "V&V Execution Checklist"
description: "Checklist for V&V Execution"
title: "[V&V]: "
labels: ["checklist"]
assignees: 
  - scarter008

body:
  - type: checkboxes
    id: lead
    attributes:
      label: "Test Engineering"
      description: "Check once tasks are complete"
      options:
        - label: Team lead determine if full or partial V&V is needed
  - type: checkboxes
    id: submit
    attributes:
      label: "Engineering"
      description: "Check once tasks are complete"
      options:
        - label: Submit application ECO to Quality 
        - label: Submit server ECO to Quality 
  - type: checkboxes
    id: quality
    attributes:
      label: "Quality"
      description: "Check once tasks are complete"
      options:
        - label: Application ECO approved 
        - label: Server ECO approved 
  - type: checkboxes
    id: ops
    attributes:
      label: "Operations"
      description: "Check once tasks are complete"
      options:
        - label: Device enrolled in MDM (as applicable)
        - label: Parse account created in correct server (as applicable)
        - label: Equipment set up for V&V execution 
  - type: checkboxes
    id: executed
    attributes:
      label: "Test Engineering"
      description: "Check once tasks are complete"
      options:
        - label: V&V Executed 
