name: "V&V Execution Checklist"
description: "Checklist for V&V Execution"
title: "[Checklist]: "
labels: ["Checklist"]
assignees: 
  - scarter008

body:
 - type: input
    attributes:
      name: "Test Engineering"
      description: "Team lead determine if full or partial V&V is needed. List sections needed."
  
