name: "detect V&V issue and dispatch it to the .github repo"

# run on new issue open
on:
  issues:
    types: 
      - opened

# first job test workflow run correct.
jobs:
  automation_job:
    name: "V&V Issue Creator job"
    runs-on: ubuntu-latest
    permissions:
      issues: read
    if: contains(github.event.issue.title, 'V&V Request')
    steps:
      # setup secret access token
      - uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.ROBOT_PERSONAL_ACCESS_TOKEN }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ROBOT_PERSONAL_ACCESS_TOKEN }}
          repository: biosensics/v-v-automation
          event-type: v-v-request
          client-payload: '{"repository_owner": "${{ github.repository_owner }}", "repository_name": "${{ github.event.repository.name }}", "title": "${{ github.event.issue.title }}", "issue_number": "${{ github.event.issue.number }}"}'
