name: "detect V&V issue and create a new issue"

# run on new issue open
on:
  issues:
    types: 
      - opened

# read the new created issue
# go through each checkboxes
# create new issue for each checkboxes
# link each new issue to specific person / group
jobs:
  test_first_job:
    name: "first job test"
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'V&V Request')
    steps:
      - name: Print something
        env:
          VAR: Hello World
          VAR2: HA HA HA
        run: |
          echo $VAR $VAR2.