name: "detect V&V issue and create a new issue"

# run on new issue open
on:
  issues:
    types: 
      - opened

# read the new created issue
# go through each checkboxes
# create new issue for each checkboxes
# link each new issue to specific person / group
jobs:
  create_issue:
    runs-on: ubuntu-latest
    # if v&v checklist
    if: startsWith(github.event.issue.title, 'V&V Request')
    steps:
      - name: create issue test