name: "detect V&V issue and create a new issue"

# run on new issue open
on:
  issues:
    types: 
      - opened

# first job test workflow run correct.
jobs:
  automation_job:
    name: "first job test"
    runs-on: ubuntu-latest
    env:
      # add all environment variables
      CURRENT_OWNER: ${{ github.repository_owner }}
      CURRENT_REPO: ${{ github.event.repository.name }}
      CURRENT_ISSUES_TITLE: ${{ github.event.issue.title }}
      CURRENT_ISSUES_ID: ${{ github.event.issue.number }}
      ENTRY_POINT: node entry.js
    permissions:
      issues: read
    if: startsWith(github.event.issue.title, 'V&V Request')
    steps:
      # setup secret access token
      - uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Install environment
        run: |
          npm install octokit
          echo npm installed
      - name: Run script
        run: $ENTRY_POINT $CURRENT_OWNER $CURRENT_REPO $CURRENT_ISSUES_ID
