name: "detect V&V issue and create a new issue"

# run on new issue open
on:
  issues:
    types: 
      - opened

# first job test workflow run correct.
jobs:
#   print_job:
#     name: "first job test"
#     runs-on: ubuntu-latest
#     if: startsWith(github.event.issue.title, 'V&V Request')
#     steps:
#       - name: Print something
#         env:
#           VAR: You got here!
#           VAR2: There is a V&V Request issue~
#         run: echo $VAR $VAR2

  read_current_issue:
    name: "read current issue"
    runs-on: ubuntu-latest
    steps:
      - name: read issue title
        env:
          CURRENT_ISSUES_TITLE: ${{ github.event.issue.title }}
          CURRENT_ISSUES_ID: ${{ github.event.id }}
        run: |
          echo CURRENT_ISSUES_TITLE: $CURRENT_ISSUES_TITLE
          echo CURRENT_ISSUES_ID: $CURRENT_ISSUES_ID
          echo CURRENT_ISSUES_ASSIGNEE: $CURRENT_ISSUES_ASSIGNEE
          echo CURRENT_ISSUES_ASSIGNER: $CURRENT_ISSUES_ASSIGNER



  # create_issue:
  #   name: "create a new issue"
  #   runs-on: ubuntu-latest
  #   needs: print_job
  #   permissions:
  #     issues: write
  #   steps:
  #     - name: Create Random Issue
  #       uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
  #       with:
  #         assignees: "YiqianDeng"
  #         labels: "v&v created issue"
  #         title: "test create random issue by create a V&V request"
  #         body: |
  #           ### Test

  #           - [ ] first step
  #           - [ ] second step
  #           - [ ] third step

  #           ### Point
  #           some points

  #         pinned: false
  #         close-previous: false
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
