name: "listen for dispatches to create v&v issues in a repo"

# run on new issue open
on:
  repository_dispatch:
    types: [v-v-request]

# first job test workflow run correct.
jobs:
  automation_job:
    name: "V&V Issue Creator job"
    runs-on: ubuntu-latest
    env:
      # add all environment variables
      CURRENT_OWNER: ${{ github.event.client_payload.repository_owner }}
      CURRENT_REPO: ${{ github.event.client_payload.repository_name }}
      CURRENT_ISSUES_TITLE: ${{ github.event.client_payload.title }}
      CURRENT_ISSUES_ID: ${{ github.event.client_payload.issue_number }}
      GITHUB_TOKEN: ${{ secrets.ROBOT_PERSONAL_ACCESS_TOKEN || github.token }}
    permissions:
      issues: read
    if: contains(github.event.client_payload.title, 'V&V Request')
    steps:
      # setup secret access token
      - uses: actions/checkout@v2
        with:
          ref: main
          token: $GITHUB_TOKEN
      - name: Install environment
        run: |
          cd v-v-checklist
          npm install
      - name: Run script
        run: node v-v-checklist/. $CURRENT_OWNER $CURRENT_REPO $CURRENT_ISSUES_ID
